services:
  weather_msp_api:    
    image: ghcr.io/dvvtech/weather-msp:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Prod      
    networks:
      - public-network5
    secrets:
      - OpenWeatherMap__ApiKey      
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.weather-msp-api.rule=Host(`api.cloud-platform.pro`) && PathPrefix(`/weathermsp`)"
        - "traefik.http.routers.weather-msp-api.entrypoints=websecure"
        - "traefik.http.routers.weather-msp-api.tls.certresolver=letsencrypt"
        - "traefik.http.services.weather-msp-api.loadbalancer.server.port=8080"
        - "traefik.http.middlewares.weather-msp-stripprefix.stripprefix.prefixes=/weathermsp"
        - "traefik.http.routers.weather-msp-api.middlewares=weather-msp-stripprefix"      

networks:
  public-network5:
    external: true
    name: public-network5

secrets:
  OpenWeatherMap__ApiKey:
    external: true  